version: '2.3'
services:  

  # reverse:
  #   container_name: reverse
  #   hostname: reverse
  #   image: nginx
  #   ports:
  #     - 8080:8081
  #   volumes:
  #     - /nginx/conf.d:/etc/nginx
    #  - /nginx/certs:/etc/ssl/private

  client:
    restart: always
    build:
      context: ./client
    command: npx http-server
    volumes:
        - ./client:/client
        #- /client/node_modules
    links:
        - api
    ports:
      - "8080:8080"
    stdin_open: true

  api:
    restart: always
    build:
        context: ./api/
    volumes:
        - ./api:/api
        #- /api/node_modules
    command: npm start
    # volumes:
    # - ./api/:/usr/app
    # - /usr/app/node_modules
    ports:
    - "3000:3000"